### Create Category
POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "Category 1",
    "description": "Category 1 Description"
}

### List Categories
GET http://localhost:3000/categories

### Create Cast Member
POST http://localhost:3000/cast-members
Content-Type: application/json

{
    "name": "Actor 1",
    "type": "directors"
}

### List CastMembers
GET http://localhost:3000/cast-members
