### Create Category
POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "Category 1",
    "description": "Category 1 Description"
}

### List Categories
GET http://localhost:3000/categories?filter=2

### Create Cast Member
POST http://localhost:3000/cast-members
Content-Type: application/json

{
    "name": "Actor 3",
    "type": 2
}

### List CastMembers with filter
GET http://localhost:3000/cast-members?type=2

### List CastMembers
GET http://localhost:3000/cast-members?sort=name&sort_dir=asc
