### Create Category
POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "Category 1",
    "description": "Category 1 Description"
}

### List Categories
GET http://localhost:3000/categories

### Create Cast Member
POST http://localhost:3000/cast-members
Content-Type: application/json

{
    "name": "Actor 2",
    "type": 1
}

### List CastMembers with filter
GET http://localhost:3000/cast-members?filter={"type": 1}

### List CastMembers
GET http://localhost:3000/cast-members?sort=name&sort_dir=asc
